# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
