# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20171209_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manager.Marca'),
        ),
    ]
