# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20171209_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
