# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20171209_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDeposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposito', to='manager.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
