# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_itemdeposito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdeposito',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ItemDeposito',
        ),
    ]
