# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20171214_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camporemito',
            name='campo_remito_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='remito',
            name='remito_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
