# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20171214_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='camporemito',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
