# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 22:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0011_camporemito_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLogs',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('action', models.BooleanField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_emitidos', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='manager.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
