# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_itemlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('precio_id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='manager.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
