# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 19:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 20, 16, 13, 12, 952654)),
        ),
    ]
