# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 19:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_precio_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='precio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='precio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 20, 16, 27, 26, 406702)),
        ),
    ]
