# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 18:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20171220_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='alarma',
            field=models.IntegerField(choices=[(0, 'No alarm'), (1, 'Alarm level LOW'), (2, 'Alarm level HIGH')], default=0),
        ),
        migrations.AlterField(
            model_name='precio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 15, 10, 26, 814324)),
        ),
    ]
