# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_auto_20171221_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='alarma',
            field=models.IntegerField(choices=[(0, 'No alarm'), (1, 'Alarm level LOW'), (2, 'Alarm level HIGH')], default=2),
        ),
        migrations.AlterField(
            model_name='precio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 15, 55, 32, 768481)),
        ),
    ]
